name: Go
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        go-version: ["1.22.x"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.x'

      - name: install templ
        run:
          go install github.com/a-h/templ/cmd/templ@latest

      - name: generate go files from templ files
        run:
          templ generate .

      - name: Install dependencies
        run: |
          go get github.com/a-h/templ
          go get github.com/labstack/echo/v4
          go get github.com/mattn/go-sqlite3

      - name: Build
        run: go build -v ./cmd/...

      - name: Test
        run: go test -v ./cmd/...
